[workspace]
members = ["app/ai-chat",
    "app/feiwen",
    "app/http-client",
    "app/novel-download",
    "app/ai-chat/extensions/url_search"
, "crates/window-ext"]

resolver = "2"

[workspace.dependencies]
gpui = "0.2.2"
gpui-component = "0.5.0"
# Optional, for default bundled assets
gpui-component-assets = "0.5.0"
window-ext = {path = "./crates/window-ext"}
