[workspace]
members = [
    "app/feiwen",
    "app/http-client",
    "app/novel-download",
    "common/components",
    "common/router",
    "common/theme",
]

resolver = "2"

[workspace.dependencies]
gpui = "0.2.2"
gpui-component = "0.5.0"
# Optional, for default bundled assets
gpui-component-assets = "0.5.0"
smallvec = "1.15.1"
