[workspace]
members = [
  "app/ai-chat",
  "app/feiwen",
  "app/http-client",
  "app/novel-download",
  "app/ai-chat/extensions/url_search",
  "crates/window-ext",
  "crates/xtask",
]

resolver = "2"

[workspace.dependencies]
gpui = "0.2.2"
gpui-component = "0.5.1"
# Optional, for default bundled assets
gpui-component-assets = "0.5.1"
window-ext = { path = "./crates/window-ext" }

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = "symbols"
debug = 0
incremental = false
