[package]
name = "ai-chat"
version = "0.1.0"
edition = "2024"

[dependencies]
# ui
gpui.workspace = true
gpui-component = { workspace = true, features = [
  "tree-sitter-languages",
] }
gpui-component-assets = {workspace = true}
rust-embed = { version = "8.9.0", features = ["interpolate-folder-path"] }
anyhow = "1.0.100"

# err
thiserror = "2.0.17"

# database
diesel = { version = "2.3.5", features = ["sqlite", "r2d2", "numeric", "time", "returning_clauses_for_sqlite_3_35","serde_json"] }
libsqlite3-sys = { version = "0.35.0", features = ["bundled-windows"] }
dirs-next = "2.0.0"
time = { version = "0.3.44", features = ["serde"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.148"
pinyin = "0.10.0"

# log
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["local-time"] }

# http request
reqwest = { version = "0.12.25", features = ["json"] }
tokio = { version = "1.48.0", features = [
    "rt",
    "rt-multi-thread",
    "sync",
    "fs",
    "io-util",
    "macros",
] }
reqwest-eventsource = "0.6.0"
futures = "0.3.31"
async-stream = "0.3.6"

# extension
wasmtime = { version = "40.0.0" }
wasmtime-wasi = "40.0.0"
get-selected-text = "0.1.6"

# config
toml = "0.9.10"

[dev-dependencies]
anyhow = "1.0.100"
